algorithm:
  match_score: 1.0
  mismatch_score: -0.9
  open_gap_score: -0.6
  extend_gap_score: -3.5
  min_score: 40.0
  max_iterations: 100

seeding:
  k: 15
  max_gap: 10
  extend: 300
  max_kmer_hits: 3

preprocessing:
  strip_chars: "\\_"

input:
  point_of_comparison: "test_data/test_data16_rebecca"
  corpus: "bjornpixel/derge_tshad_split_ewts"
  # dir: "test_data/test_data8_rebecca"
  # dir: "test_data/test_data5_rebecca"
  # dir: "test_data/test_data7_sonam"
  # dir: "test_data/test_data13_nicola"
  # dir: "test_data/test_data5_rebecca"

output:
  # path: "output/sonam_testdata14_vs_kangyur.csv"
  # path: "output/test_data5_rebecca.csv"
  # path: "output/test_data7_sonam.csv"
  # path: "output/test_data13_nicola.csv"
  path: "output/rebecca_D2672_vs_derge.csv"