algorithm:
  match_score: 1.0
  mismatch_score: -1.2
  open_gap_score: -0.6
  extend_gap_score: -3.5
  min_score: 10.0
  max_iterations: 100

seeding:
  k: 5
  max_gap: 10
  extend: 50
  max_kmer_hits: 3

preprocessing:
  strip_chars: "\\_"
  token_mode: syllable

input:
  point_of_comparison: "test_data/test_data16_rebecca"
  corpus: "user_byangchub_run/corpus"

output:
  stock_phrase_detection: true
  path: "output/results.csv"

parallel:
  workers: 8
